name: build
on:
  push
jobs:
  build:
    name: my job
    runs-on: ubuntu-latest
    steps:
    - name: my first step
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Nhut
        LAST_NAME: Pham
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.