name: First Workflow
on: [ push, workflow_dispatch ]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: my first step
      env:
        FIRST_NAME: Nhut
        LAST_NAME: Pham
      run: |
        echo "Hello World"
        echo "My name is " $FIRST_NAME $LAST_NAME
    - name: my second step
      if: success()
      run: echo "Done - Bye"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v3
    - name: install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: build
      run: |
        mkdir dist
        touch dist/test.txt
        touch package.json
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: |
          dist
          package.json
        
