name: First Workflow
on: [ push, workflow_dispatch ]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: my first step
      env:
        FIRST_NAME: Nhut
        LAST_NAME: Pham
      run: |
        echo "Hello World"
        echo "My name is " $FIRST_NAME $LAST_NAME
    - name: my second step
      if: success()
      run: echo "Done - Bye"
  build-job:
    needs: first-job
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish-step.outputs.script-file }}
    steps:
    - name: get code
      uses: actions/checkout@v3
    - name: install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: build
      run: |
        echo "package file" > package.json
        mkdir dist
        cd dist && mktemp XXXXXXXXXX.$(mktemp -u XXX)
    - name: publish file
      id: publish-step
      run: find dist/*.txt -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: |
          dist
          package.json
  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist-files
    - name: output content
      run: |
        ls
        ls dist
    - name: output filename
      run: echo ${{ needs.build-job.outputs.script-file }}
    - name: deploy
      run: echo "deploying..."
