name: First Workflow
on: [ push, workflow_dispatch ]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: my first step
      env:
        FIRST_NAME: Nhut
        LAST_NAME: Pham
      run: |
        echo "Hello World"
        echo "My name is " $FIRST_NAME $LAST_NAME
    - name: my second step
      if: success()
      run: echo "Done - Bye"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
    - name: my third step
      run: echo "executing third step..."
