name: Resuable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: artifact file name
        required: false
        type: string
        default: dist
    outputs:
      result:
        description: result of deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    secrets:
      username:
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: output content
        run: |
          ls
          ls dist
      - name: output information
        run: |
          echo "deploying & uploading..."
          echo "db username" ${{ secrets.username }}
      - name: set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
