name: Resuable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: artifact file name
        required: false
        type: string
        default: dist-files
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: output information
        run: echo "deploying & uploading..."
