name: Use Resuable Deploy
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: using reusable deploy
        run: echo "using reusable deploy"
      - name: build
        run: |
          echo "test 1" > test1.txt
          mkdir dist
          cd dist
          mktemp XXXXXXXXXX.$(mktemp -u XXX)
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            test1.txt
  deploy:
    needs: info
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: dist-files
    secrets:
      username: ${{ secrets.DB_USERNAME }}
  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: print deploy output
        run: echo ${{ needs.deploy.outputs.result }}
    
